title: Messy Wires
description: A complete guide to Visual Programming best practices using Grasshopper
themeConfig:
  logo: /paramdigma-black-large.svg
  displayAllHeaders: true
  activeHeaderLinks: true
  sidebar:
    - /preface/
    - /introduction/
    - /chapters/data-trees/
    - /chapters/keep-it-tidy/
    - /chapters/advanced-components/
    - /chapters/best-practices/
    - /chapters/teamwork/
    - /chapters/interoperability/
    - /conclusion/
  nav:
    - text: Home
      link: /
    - text: Book
      link: /introduction
    - text: Author
      link: 'https://paramdigma.com'
  repo: paramdigma/messy-wires
  repoLabel: Contribute!
  editLinks: true
  editLinkText: Help us improve this page!
  lastUpdated: true
head:
  - - 'script'
    - data-ad-client: 'ca-pub-9365287716304588'
      async: true
      src: 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'
plugins:
  - 'vuepress-plugin-typescript'
  - 'vuepress-plugin-catalog-graph'
  - 'flowchart'
